spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rigsheets}
    username: ${DB_USER:rigsheets}
    password: ${DB_PASS:change_this_pw}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate      # safer than update for prod (lets Flyway manage schema)

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true