spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.50.32}:${DB_PORT:5432}/${DB_NAME:rigsheets}
    username: ${DB_USER:rigsheets}
    password: ${DB_PASS:change_this_pw}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origins:
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
            # add your LAN IP if you test from phones/tablets:
            # - "http://192.168.1.10:3000"
          allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
          allowed-headers: [ "*" ]
          exposed-headers: [ "Location" ]
          allow-credentials: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate      # safer than update for prod (lets Flyway manage schema)

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha